# Website details
name: A-1 Fansub
description: Bebas Layaknya Awan~
author: A-1
lang: Indonesia
locale: Indonesia

# Jekyll
paginate: 10
highlighter: rouge
markdown: kramdown
plugins: [jekyll-paginate]
timezone: Indonesia
paginateLabel: page
paginate_path: "page/"
permalink: /:categories/:year/:month/:day/:title
baseurl: https://a-1fansub.github.io/

# Includes
addthisId: ""
disqusUsername: ""
googleAnalyticsId: ""

# Search engine verifications
bing: ""
yandex: ""
google: ""

# Sitemap
sitemap:
  file: "/sitemap.xml"
  exclude:
    - "/404.html"
  include_posts:
    - "/index.html"
  change_frequency_name: "daily"
  priority_name: "1.00"

#theme
navbar-col: "#152232"
navbar-text-col: "#76a4bf"
navbar-border-col: "#152232"
page-col: "#0b1622"
text-col: "#b4a996"
link-col: "#39a6d8"
hover-col: "#0085A1"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"
