# Website details
name: A-1 Fansub
description: Bebas Layaknya Awan~
author: A-1
lang: id
locale: id

# Jekyll
paginate: 10
highlighter: rouge
markdown: kramdown
plugins: [jekyll-paginate]
timezone: Indonesia
paginateLabel: page
paginate_path: "page/"
permalink: /:title
baseurl: https://a-1fansub.github.io

# Includes
addthisId: ""
disqusUsername: ""
googleAnalyticsId: ""

# Search engine verifications
bing: ""
yandex: ""
google: ""

# Sitemap
sitemap:
  file: "/sitemap.xml"
  exclude:
    - "/404.html"
  include_posts:
    - "/index.html"
  change_frequency_name: "daily"
  priority_name: "1.01"
